# covariance matrix

In [5]:
import numpy as np

x_1 = np.array([2, 1])
x_2 = np.array([2, 4])
x_3 = np.array([4, 1])
x_4 = np.array([4, 3])

X = np.array([x_1, x_2, x_3, x_4])
X_mean = np.mean(X, axis=0)
X = X - X_mean
X   # 원점으로 돌려주기

array([[-1.  , -1.25],
       [-1.  ,  1.75],
       [ 1.  , -1.25],
       [ 1.  ,  0.75]])

In [6]:
# 1, 0에 투영하기
u = np.array([1, 0])

np.dot(X, u)

array([-1., -1.,  1.,  1.])

In [22]:
# 공분산 행렬
np.dot(X.T, X) / 4

array([[ 1.    , -0.25  ],
       [-0.25  ,  1.6875]])

In [24]:
# 고유값, 고유벡터 
np.linalg.eig(np.dot(X.T, X) / 4)

(array([0.91870405, 1.76879595]),
 array([[-0.95098267,  0.30924417],
        [-0.30924417, -0.95098267]]))