# covariance matrix

In [5]:
import numpy as np

x_1 = np.array([2, 1])
x_2 = np.array([2, 4])
x_3 = np.array([4, 1])
x_4 = np.array([4, 3])

X = np.array([x_1, x_2, x_3, x_4])
X_mean = np.mean(X, axis=0)
X = X - X_mean
X   # 원점으로 돌려주기

array([[-1.  , -1.25],
       [-1.  ,  1.75],
       [ 1.  , -1.25],
       [ 1.  ,  0.75]])

In [6]:
# 1, 0에 투영하기
u = np.array([1, 0])

np.dot(X, u)

array([-1., -1.,  1.,  1.])

In [22]:
# 공분산 행렬
np.dot(X.T, X) / 4

array([[ 1.    , -0.25  ],
       [-0.25  ,  1.6875]])

In [24]:
# 고유값, 고유벡터 
np.linalg.eig(np.dot(X.T, X) / 4)

(array([0.91870405, 1.76879595]),
 array([[-0.95098267,  0.30924417],
        [-0.30924417, -0.95098267]]))

### 6.1 [예제 6-1]에서 초 기 군 집 중 심 을 z_1 = x_2, z_2 = x_3, z_3 = x_7 로 다 시 설 정 했 을 때 k - 평 균 의 동작을예제처럼보이시오. 다중시작을사용한다면둘중어느해를취할지판단하시오.
![Alt text](image-1.png)

In [1]:
# 예제 6-1



# 문제

[1 1 2 2 0 0 0]


/opt/homebrew/Caskroom/miniconda/base/envs/estud/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


### 6.3 [문제6-1]의초기군집중심과문제1의초기군집중심각에k-medbids 알고리즘을적용 하시오.

### 6.10 훈련집합이다음과같다. PCA를이용하여3차원을2차원으로변환하는행렬을구하시오.