#### 1. $A$의 $2A, A^T, A^{-1}$을 쓰시오. 또한 A의 계수를 쓰시오

In [27]:
import numpy as np

A = np.array([[1, -2, 3, 5], [2, 2, -1, 0], [3, 0, 1, 2], [1, 0, 2, 0]])

In [28]:
A_2 = 2 * A
print(A_2)

[[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]


In [29]:
A_transpose = A.T
print(A_transpose)

[[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]


In [30]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


#### 2. A의 $A^{1/2}, A^{-1/2}$를 구하시오.

In [31]:
A = np.array([[1, -2], [2, 2]])

In [32]:
from scipy import linalg

A_sqrt = linalg.sqrtm(A)
A_sqrt

array([[ 1.22735265+9.81982781e-17j, -0.71161403+9.18378584e-17j],
       [ 0.71161403-1.01538774e-17j,  1.58315967-1.32267475e-16j]])

In [33]:
A_inv_sqrt = np.linalg.inv(A_sqrt)
A_inv_sqrt

array([[ 0.64632223-3.30332338e-17j,  0.29051521-2.80692146e-17j],
       [-0.29051521-5.27813099e-18j,  0.50106462+5.63422987e-17j]])