<a href="https://colab.research.google.com/github/yesinkim/MachineLearningStudy/blob/main/chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. $A$의 $2A, A^T, A^{-1}$을 쓰시오. 또한 A의 계수를 쓰시오

In [15]:
import numpy as np

A = np.array([[1, -2, 3, 5], [2, 2, -1, 0], [3, 0, 1, 2], [1, 0, 2, 0]])

In [16]:
A_2 = 2 * A
print(A_2)

[[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]


In [17]:
A_transpose = A.T
print(A_transpose)

[[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]


In [18]:
A_inverse = np.linalg.inv(A)
print(A_inverse)

[[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


#### 2. A의 $A^{1/2}, A^{-1/2}$를 구하시오.

In [19]:
A = np.array([[1, -2], [2, 2]])

In [20]:
from scipy import linalg

A_sqrt = linalg.sqrtm(A)
A_sqrt

array([[ 1.22735265+1.11022302e-16j, -0.71161403+0.00000000e+00j],
       [ 0.71161403-5.55111512e-17j,  1.58315967+0.00000000e+00j]])

In [21]:
A_inv_sqrt = np.linalg.inv(A_sqrt)
A_inv_sqrt

array([[ 0.64632223-3.59544841e-17j,  0.29051521-1.61611718e-17j],
       [-0.29051521+3.88235044e-17j,  0.50106462+1.74507670e-17j]])

#### Q4. 변수가 4개인 다음 2차 다항식 2개를 예제2-1처럼 행렬로 표시하시오. 행렬을 더함으로써 다항식 덧셈 f_1(x)+f_2(x)를 수행할 수 있다는 사실을 이 예제를 이용하여 보이시오.

In [22]:
f1_2 = np.array([[-2, -1.5, 0, 3.1], [2, 2, 0, -6], [-2.1, 0, 3, 0], [2, 3, 0, -2]])
f1_1 = np.array([1.2, 3.3, 0, -4])
f1_0 = 4.2

f2_2 = np.array([[3, 0, 3.5, -3.1], [2.1, -2, 0, -2], [-2.5, 0, 3, 0], [3, -6, 2, 0]])
f2_1 = np.array([2.2, 2.3, 3.3, -2])
f2_0 = 5.1

In [23]:
sum_2 = f1_2 + f2_2
sum_1 = f1_1 + f2_1
sum_0 = f1_0 + f1_0

In [27]:
sum_2

array([[ 1. , -1.5,  3.5,  0. ],
       [ 4.1,  0. ,  0. , -8. ],
       [-4.6,  0. ,  6. ,  0. ],
       [ 5. , -3. ,  2. , -2. ]])

In [28]:
sum_1

array([ 3.4,  5.6,  3.3, -6. ])

In [29]:
sum_0

8.4

#### Q5. norm을 계산하세요.

In [33]:
x = np.array([3, -4, -1.2, 0, 2.3])

print(np.linalg.norm(x, 1))
print(np.linalg.norm(x, 2))
print(np.linalg.norm(x, 3))
print()

10.5
5.632938842203065
4.716120891176797
4.0
